package br.com.barbershop.ui;

import br.com.barbershop.model.Session;
import br.com.barbershop.service.SessionService;
import br.com.barbershop.app.AppContext;
import br.com.barbershop.app.FabricaDeServicos;
import br.com.barbershop.ui.support.UIUtil;
import javax.swing.JOptionPane;

/**
 * Tela de login: autentica o usuário e abre a {@link TelaHome}. É a
 * primeira tela exibida quando já existe uma barbearia cadastrada (ver
 * {@link br.com.barbershop.app.Main}); caso contrário, o app abre direto
 * em {@link TelaCadastroInicial}.
 * Gerada com GUI Builder do NetBeans - não editar o método initComponents().
 */
public class TelaLogin extends javax.swing.JFrame {

    private SessionService sessionService;

    /** Monta a tela e aplica o ícone do app; a sessão em si só começa ao clicar em "Entrar". */
    public TelaLogin() {
        initComponents();
        UIUtil.aplicarLogo(lblLogo, 88, 88);
        UIUtil.estilizarBotaoPrimario(btnEntrar);
        UIUtil.aplicarIcone(this);
        this.sessionService = new FabricaDeServicos().criarSessionService();
        pack();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Barbershop - Login");
        setResizable(false);

        lblLogo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setText("Barbershop");

        jLabel1.setText("Login:");

        jLabel2.setText("Senha:");

        btnEntrar.setBackground(new java.awt.Color(51, 51, 51));
        btnEntrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtLogin)
                    .addComponent(txtSenha)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblLogo)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        String login = txtLogin.getText().trim();
        String senha = new String(txtSenha.getPassword());

        if (login.isEmpty() || senha.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha login e senha", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Session session = sessionService.iniciarSessao(login, senha);
            if (session == null) {
                JOptionPane.showMessageDialog(this, "Login ou senha inválidos", "Erro", JOptionPane.ERROR_MESSAGE);
                txtSenha.setText("");
                txtSenha.requestFocusInWindow();
                return;
            }

            // Persistir a sessão pra que as demais telas saibam quem está logado e em qual barbearia
            AppContext.getInstance().setSessaoAtual(session);

            new TelaHome().setVisible(true);
            this.dispose();
        } catch (java.sql.SQLException ex) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao acessar o banco de dados:\n" + ex.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalStateException ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "Configuração necessária", JOptionPane.WARNING_MESSAGE);
        }
    }                                         
// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
